### ISSUE TITLE
Error when setting up plugin / adding accessories

### ISSUE THREAD

**Issue by ladooee** [valiquette/homebridge-ambient-realtime#1]
Hi, I have a WS2902 station I am trying to get realtime data from in HomeKit. This is the error I get after successfully getting "initial data from subscribed event" in my log.

```
TypeError: this.station.createAccessory is not a function
    at /var/lib/homebridge/node_modules/homebridge-ambient-realtime/ambientplatform.cjs:146:43
    at Array.forEach (<anonymous>)
    at ambientPlatform.addAccessory (/var/lib/homebridge/node_modules/homebridge-ambient-realtime/ambientplatform.cjs:126:11)
    at Socket.<anonymous> (/var/lib/homebridge/node_modules/homebridge-ambient-realtime/ambientplatform.cjs:101:8)
    at Socket.Emitter.emit (/var/lib/homebridge/node_modules/homebridge-ambient-realtime/node_modules/@socket.io/component-emitter/lib/cjs/index.js:143:20)
    at Socket.emitEvent (/var/lib/homebridge/node_modules/homebridge-ambient-realtime/node_modules/socket.io-client/build/cjs/socket.js:559:20)
    at Socket.onevent (/var/lib/homebridge/node_modules/homebridge-ambient-realtime/node_modules/socket.io-client/build/cjs/socket.js:546:18)
    at Socket.onpacket (/var/lib/homebridge/node_modules/homebridge-ambient-realtime/node_modules/socket.io-client/build/cjs/socket.js:514:22)
    at Manager.Emitter.emit (/var/lib/homebridge/node_modules/homebridge-ambient-realtime/node_modules/@socket.io/component-emitter/lib/cjs/index.js:143:20)
    at /var/lib/homebridge/node_modules/homebridge-ambient-realtime/node_modules/socket.io-client/build/cjs/manager.js:246:18
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
```

Which I assume is related to this line in ambientplatform.cjs? 

`this.accessories[uuid]=this.station.createAccessory(device, uuid, this.accessories[uuid])`

My understanding breaks down after that. The only specific weather station model I see referenced in the code is WS4000, maybe this plugin isn't compatible with all stations? Not sure why that would be the case though.

**Comment by valiquette** [comment]
This plugin is a bit of work in progress. I know there are some issues in the latest version which was trying to get through verification process. turns out is was the script and not the plugin. I should have an update in a day or two. In the meantime you could try installing the first version 0.1.3 that version should work fine. The reference to W4000 is just text it has nothing to do with any station, your's should work fine. Please let me know.

**Comment by ladooee** [comment]
Got it, I didn't realize you had just made this! I tried rolling back to 0.1.3 and I get to `initial data from subscribed event` in the log. But then I get the error:

```
TypeError: Cannot read properties of undefined (reading 'length')
    at /var/lib/homebridge/node_modules/homebridge-ambient-realtime/ambientplatform.js:283:26
    at Array.forEach (<anonymous>)
    at ambientPlatform.addAccessory (/var/lib/homebridge/node_modules/homebridge-ambient-realtime/ambientplatform.js:126:11)
    at Socket.<anonymous> (/var/lib/homebridge/node_modules/homebridge-ambient-realtime/ambientplatform.js:101:8)
    at Socket.Emitter.emit (/var/lib/homebridge/node_modules/homebridge-ambient-realtime/node_modules/@socket.io/component-emitter/lib/cjs/index.js:143:20)
    at Socket.emitEvent (/var/lib/homebridge/node_modules/homebridge-ambient-realtime/node_modules/socket.io-client/build/cjs/socket.js:559:20)
    at Socket.onevent (/var/lib/homebridge/node_modules/homebridge-ambient-realtime/node_modules/socket.io-client/build/cjs/socket.js:546:18)
    at Socket.onpacket (/var/lib/homebridge/node_modules/homebridge-ambient-realtime/node_modules/socket.io-client/build/cjs/socket.js:514:22)
    at Manager.Emitter.emit (/var/lib/homebridge/node_modules/homebridge-ambient-realtime/node_modules/@socket.io/component-emitter/lib/cjs/index.js:143:20)
    at /var/lib/homebridge/node_modules/homebridge-ambient-realtime/node_modules/socket.io-client/build/cjs/manager.js:246:18
```

Thanks for working on this, I will keep an eye out for updates

**Comment by valiquette** [comment]
This is now fixed in the latest version 0.1.6

sorry about that

**Comment by valiquette** [comment]
error reading 'length' occurred when no customer sensors are defined. I corrected that issue. Try the latest version.

**Comment by ladooee** [comment]
Hey, it works! Definitely getting information quicker than the 2 minute polling version. I am getting an erroneous low battery warning, on the ambientweather.net site it says all batteries are good, but the indoor sensor is showing low battery in homekit/homebridge.

**Comment by valiquette** [comment]
Somewhat not surprising, ambient is not consistant with their battery status it woudl have been very easy to miss one. Can you tell me what device you have that is showing battery low? This would be a very simple fix. 
This link may be helpful https://github.com/ambient-weather/api-docs/wiki/Device-Data-Specs
Are you a Metrobridge user?

**Comment by valiquette** [comment]
I would be very helpful if you could attach the output for the initial data that is shown in the log when the plugin starts.

**Comment by ladooee** [comment]
Thanks for all the help. I am using this device: https://ambientweather.com/ws-2902-smart-weather-station

Specifically the indoor console (WS-2902D) is reporting low battery (in homekit/homebridge). And based off the data stream it looks like it's just not picking up a battery reading for "battin." Probably because it's plugged in? I have batteries in it but I wonder if it doesn't keep an eye on their status since it's plugged in. Either way, probably just need to update the plugin to not show battery status for meters that don't populate that field.

`[04/10/2024, 12:57:03] [Ambient] initial data from subscribed event {
  "dateutc": 1728071760000,
  "tempf": 92.5,
  "humidity": 25,
  "windspeedmph": 0.45,
  "windgustmph": 1.12,
  "maxdailygust": 4.47,
  "winddir": 308,
  "uv": 5,
  "solarradiation": 573.31,
  "hourlyrainin": 0,
  "eventrainin": 0,
  "dailyrainin": 0,
  "weeklyrainin": 0,
  "monthlyrainin": 0,
  "totalrainin": 17.539,
  "battout": 1,
  "tempinf": 74.5,
  "humidityin": 52,
  "baromrelin": 29.849,
  "baromabsin": 29.864,
  "feelsLike": 89.72,
  "dewPoint": 51.51,
  "feelsLikein": 74.1,
  "dewPointin": 55.7,
  "lastRain": "2024-05-05T11:52:00.000Z",
  "deviceId": "64b72f944c35f1d14856e7fe",
  "tz": "America/Los_Angeles",
  "date": "2024-10-04T19:56:00.000Z"
}`

**Comment by ladooee** [comment]
Thanks for all the help. I am not using MeteoBridge. I am using this device: https://ambientweather.com/ws-2902-smart-weather-station

Specifically the indoor console (WS-2902D) is reporting low battery (in homekit/homebridge). And based off the data stream it looks like it's just not picking up a battery reading for "battin." Probably because it's plugged in? I have batteries in it but I wonder if it doesn't keep an eye on their status since it's plugged in. Either way, probably just need to update the plugin to not show battery status for meters that don't populate that field.

```
[04/10/2024, 12:57:03] [Ambient] initial data from subscribed event {
  "dateutc": 1728071760000,
  "tempf": 92.5,
  "humidity": 25,
  "windspeedmph": 0.45,
  "windgustmph": 1.12,
  "maxdailygust": 4.47,
  "winddir": 308,
  "uv": 5,
  "solarradiation": 573.31,
  "hourlyrainin": 0,
  "eventrainin": 0,
  "dailyrainin": 0,
  "weeklyrainin": 0,
  "monthlyrainin": 0,
  "totalrainin": 17.539,
  "battout": 1,
  "tempinf": 74.5,
  "humidityin": 52,
  "baromrelin": 29.849,
  "baromabsin": 29.864,
  "feelsLike": 89.72,
  "dewPoint": 51.51,
  "feelsLikein": 74.1,
  "dewPointin": 55.7,
  "lastRain": "2024-05-05T11:52:00.000Z",
  "deviceId": "removed",
  "tz": "America/Los_Angeles",
  "date": "2024-10-04T19:56:00.000Z"
}
```

**Comment by valiquette** [comment]
Update will correct this. You were correct on the battery not being reported. I saw this with my WS4000 not having any outdoor battery. I took your suggestion and now both indoor and outdoor will look for a battery and only add the battery service if one is there. It will check and adjust this if needed on each boot.

**Comment by ladooee** [comment]
Thanks so much for working on this! I updated, but my indoor sensor is still showing low battery. I tried removing the cached accessories in homebridge. It re-added them upon a restart of the process, including the indoor battery accessory. Interesting that I got 4 battery low messages but then it stopped.

```
[05/10/2024, 07:04:01] [Ambient] initial data from subscribed event {
  "dateutc": 1728136980000,
  "tempf": 58.5,
  "humidity": 73,
  "windspeedmph": 0,
  "windgustmph": 0,
  "maxdailygust": 0,
  "winddir": 334,
  "uv": 0,
  "solarradiation": 1.89,
  "hourlyrainin": 0,
  "eventrainin": 0,
  "dailyrainin": 0,
  "weeklyrainin": 0,
  "monthlyrainin": 0,
  "totalrainin": 17.539,
  "battout": 1,
  "tempinf": 66.7,
  "humidityin": 54,
  "baromrelin": 29.899,
  "baromabsin": 29.914,
  "feelsLike": 58.5,
  "dewPoint": 49.87,
  "feelsLikein": 66.7,
  "dewPointin": 49.5,
  "lastRain": "2024-05-05T11:52:00.000Z",
  "deviceId": "64b72f944c35f1d14856e7fe",
  "tz": "America/Los_Angeles",
  "date": "2024-10-05T14:03:00.000Z"
}
[05/10/2024, 10:56:35] [Ambient] Battery Status Low
[05/10/2024, 10:58:37] [Ambient] Battery Status Low
[05/10/2024, 10:58:40] [Ambient] Battery Status Low
[05/10/2024, 10:58:44] [Ambient] Battery Status Low
```

**Comment by ladooee** [comment]
Thanks so much for working on this! I updated, but my indoor sensor is still showing low battery. I tried removing the cached accessories in homebridge. It re-added them upon a restart of the process, including the indoor battery accessory. Interesting that I got 4 battery low messages but then it stopped. Also just realized they are a few hours after the initial data.

```
[05/10/2024, 07:04:01] [Ambient] initial data from subscribed event {
  "dateutc": 1728136980000,
  "tempf": 58.5,
  "humidity": 73,
  "windspeedmph": 0,
  "windgustmph": 0,
  "maxdailygust": 0,
  "winddir": 334,
  "uv": 0,
  "solarradiation": 1.89,
  "hourlyrainin": 0,
  "eventrainin": 0,
  "dailyrainin": 0,
  "weeklyrainin": 0,
  "monthlyrainin": 0,
  "totalrainin": 17.539,
  "battout": 1,
  "tempinf": 66.7,
  "humidityin": 54,
  "baromrelin": 29.899,
  "baromabsin": 29.914,
  "feelsLike": 58.5,
  "dewPoint": 49.87,
  "feelsLikein": 66.7,
  "dewPointin": 49.5,
  "lastRain": "2024-05-05T11:52:00.000Z",
  "deviceId": "removed",
  "tz": "America/Los_Angeles",
  "date": "2024-10-05T14:03:00.000Z"
}
[05/10/2024, 10:56:35] [Ambient] Battery Status Low
[05/10/2024, 10:58:37] [Ambient] Battery Status Low
[05/10/2024, 10:58:40] [Ambient] Battery Status Low
[05/10/2024, 10:58:44] [Ambient] Battery Status Low
```

**Comment by valiquette** [comment]
you should not even have a battery for the indoor sensor. It works fine for the outdoor sensor, I will check and see if I missed something.

**Comment by valiquette** [comment]
ok I fixed it in new update, I had a reference to battout instead of battin. 

The 4 alerts you saw, those do not come direct from the once a minute update, they appear in the log when HomeKit get the value for that sensor, so that would be normal.

**Comment by ladooee** [comment]
Got it, thanks for all the updates. Everything's working on my end!
