### ISSUE TITLE
No issue...just a huge THANK YOU!

### ISSUE THREAD

**Issue by threeonparfive** [valiquette/homebridge-ambient-realtime#3]
The whole reason I got my Ambient station was to measure wind speed and then turn something off when it got too high.  The only way I've been able to do this so far has been by proxy through Weather Underground and a plug-in to pull from there.  It has worked, but not great, and certainly unnecessary complexity for my needs, not to mention a reliance on a 3rd party.

I'm so thankful that someone has finally created a fully functional Ambient Weather plugin to pull data from the source.  And not only that, you had the vision to do one better by having the option to create multiple HomeKit sensors for the same Ambient sensor!  You've allowed me to have 2 different wind speed thresholds to control different things that are impacted by different wind speeds.  Thanks so much and keep up the awesome work!

Not that I have a need for any other Ambient sensors that I can think of but it would be appreciated if you could share the documentation for all of the available data point options for plug-in sensors.

**Comment by valiquette** [comment]
Thank you, 
I'll see about adding some additional info to the readme.
There is not a lot of documentation 
https://github.com/ambient-weather/api-docs/wiki/Device-Data-Specs
When the plugin loads it displays everything Ambient is reporting in the homebridge log and any of those items can be used for a sensor.
